package Opgave4;



public class TrainProtocolNotFoundException extends ClassNotFoundException {

	// AUTO generated by eclipse
	private static final long serialVersionUID = 5144568206693121846L;

	public TrainProtocolNotFoundException(String s) {
		super(s);
	}
}
